services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    depends_on:
      mysqldb:
        condition: service_healthy  # Ensure mysqldb is healthy before starting the app
    image: houssembo/tp-foyer:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    stdin_open: true
    tty: true

volumes:
  db:
