global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['172.17.0.1:8080']  # Adjust this to your Jenkins instance if needed

  - job_name: 'tp-foyer'
    static_configs:
      - targets: ['app-foyer:8089']  # Replace with the actual metrics endpoint if different
